@Restaurants_HostAddress = https://localhost:7049


GET {{Restaurants_HostAddress}}/api/weatherforecast/2/GetWeatherForecast?one=1
Accept: application/json

###

@ResultCount=0
POST {{Restaurants_HostAddress}}/api/weatherforecast/Generate?ResultCount=-1
Content-Type: application/json

{
  "min": -23,
  "max": 23
}

###
