@Restaurants_HostAddress = https://localhost:7049


GET {{Restaurants_HostAddress}}/api/Restaurants

Accept: application/json


###
GET {{Restaurants_HostAddress}}/api/Restaurants/5

###

@ResultCount=0
POST {{Restaurants_HostAddress}}/api/Restaurants
Content-Type: application/json

{
  "Name": "koke",
  "Description": "koke foods",
  "Category": "indian",
  "HasDelivery": true,
  "ContactEmail": "koke@gmail.com",
  "ContactNumber": "01117660228",
  "Street": "koke streat",
  "City": "monofia",
  "ZipCode": "77-111"
}
